[package]
name = "rand-wave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
hound = "3.5.1"
rand = "0.8.5"
walkdir = "2.4.0"
