[package]
name = "model"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
hound = "3.5.1"
rand = "0.8.5"
rayon = "1.8.0"
tch = { version = "0.14.0" }
